### ISSUE TITLE
'Context' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-hub#181]
Getting this in nodejs

```typescript
import {Context} from '@textile/textile';
...
const ctx = new Context();
```

<img width="630" alt="Screen Shot 2020-05-22 at 2 06 57 PM" src="https://user-images.githubusercontent.com/370259/82709471-84986100-9c35-11ea-8272-2aa6ca71cea5.png">

just using the default tsconfig

```
{
  "compilerOptions": {
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
    "strict": true,                           /* Enable all strict type-checking options. */
    "esModuleInterop": true,                  /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    "skipLibCheck": true,                     /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true  /* Disallow inconsistently-cased references to the same file. */
  }
}
```

**Comment by carsonfarmer** [comment]
What do you think of the above proposed solution @andrewxhill? In buckets, we don't _care_ if you are using Context (the full class) or not, just that it satisfies the minimal interface. So we could simple call this interface something like `BucketContext` and then, for convinience, export Context (the full class from @textile/context`) as is. Seem reasonable?

The goal here is to make context handy to have around, but each individual sub-package only require a very simple interface.
