### ISSUE TITLE
Websocket transport constructed with non-https:// or http:// host

### ISSUE THREAD

**Issue by yoannmtr** [textileio/js-hub#198]
Hi,

I'm trying to run the js example: [hub-browser-auth-app](https://github.com/textileio/js-examples/tree/master/hub-browser-auth-app)

I've followed the README instructions (copied the .env file and replaced the values, installed the packages on my machine...), but when I go to http://localhost:3000, I get the following error in my browser console

`Websocket transport constructed with non-https:// or http:// host`

![image](https://user-images.githubusercontent.com/1032577/83268541-11a76100-a1c6-11ea-98e2-e2b379a22ef6.png)

Did I miss any mandatory step?

Thank you in advance for your help

Best,

**Comment by andrewxhill** [comment]
_Just noting that this issue has been migrated from the js-examples repo as we are going to try and consolidate issues here._

Could you check your code and be sure you are using 'http://localhost/...' for the API requests and not 'http://127.0.0.1/...` or other?

**Comment by yoannmtr** [comment]
Thanks for your quick reply

Yes absolutely, I'm using http://localhost:3000 and not http://127.0.0.1:3000

I've made some debugging and it looks like the issue comes from the context I get here:
https://github.com/textileio/js-examples/blob/master/hub-browser-auth-app/src/server/hub-helpers.ts#L20

If I log the context I get from this line like this:
```
const apiCtx = new Context(process.env.API || null);
console.dir(apiCtx);
```
I get:
```
Context {
  _context: { host: null, transport: [Function], debug: false } }
```

(so host is null)

If I force the host when the context is created, so like this for example:
```
const apiCtx = new Context(process.env.API || 'https://api.textile.io:3447');
```

Everything works like a charm, no issue anymore

Not sure if it's a browser/os issue, but in case it helps, I'm running the example on Ubuntu 18.04 LTS and tested it in Firefox 76.0.1 and Chromium  81.0.4044.138

I cloned the repo yesterday, here are my dependencies from package.json
```
"dependencies": {
    "@textile/context": "^0.4.1",
    "@textile/textile": "^0.3.1",
    "@textile/threads-client": "^0.5.1",
    "@textile/threads-core": "^0.1.13",
    "dotenv": "^8.2.0",
    "emittery": "^0.7.0",
    "isomorphic-ws": "^4.0.1",
    "jdenticon": "^2.2.0",
    "koa": "^2.12.0",
    "koa-bodyparser": "^4.3.0",
    "koa-json": "^2.0.2",
    "koa-logger": "^3.2.1",
    "koa-route": "^3.2.0",
    "koa-router": "^8.0.8",
    "koa-send": "^5.0.0",
    "koa-static": "^5.0.0",
    "koa-websocket": "^6.0.0",
    "ws": "^7.3.0"
  },
  "devDependencies": {
    "@types/koa": "^2.11.3",
    "@types/koa-bodyparser": "^4.3.0",
    "@types/koa-json": "^2.0.18",
    "@types/koa-logger": "^3.1.1",
    "@types/koa-router": "^7.4.1",
    "@types/lodash": "^4.14.153",
    "chai": "^4.2.0",
    "chai-http": "^4.3.0",
    "copy-webpack-plugin": "^6.0.1",
    "expose-loader": "^0.7.5",
    "lodash": "^4.17.15",
    "mocha": "^7.2.0",
    "node-dev": "^4.0.0",
    "npm-run-all": "^4.1.5",
    "rimraf": "^3.0.2",
    "ts-loader": "^7.0.5",
    "ts-node-dev": "^1.0.0-pre.44",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "typescript": "^3.9.3",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11"
  },
```

Otherwise the /simple.html page works without any issue 

Best,

**Comment by Jewcub** [comment]
Was getting this error too. Solved by adding textile's server as a host. The .env needs to have a line API=https://api.textile.io:3447
devs, please add this to the example.env

**Comment by andrewxhill** [comment]
Okay! I'll remove the API flag completely, other changes I made make it just get in the way. 

Re. the context issues @yoannmtr, we've updated the libraries so you mostly don't have to deal with contexts at all anymore. Take a look at the latest and let us know if you still have any issues.
