### ISSUE TITLE
User token with the react-todo example

### ISSUE THREAD

**Issue by tatecarson** [textileio/js-hub#199]
I am attempting to get the react-todo example running. I realized that it has a hardcoded token. What code do I need to add to get this example to work? 

I have the CLI setup and have created account and user keys but I am not sure what to do next.

**Comment by andrewxhill** [comment]
Just noting that this issue has been migrated from the js-examples repo. The issue refers to the example https://github.com/textileio/js-examples/tree/master/react-todo

**Comment by andrewxhill** [comment]
all new examples! they're explained in the tutorials section of docs now, e.g. https://docs.textile.io/tutorials/hub/web-app/
