### ISSUE TITLE
Unable to access 'Files' collection

### ISSUE THREAD

**Issue by vasa-develop** [textileio/js-hub#201]
In the `react-filebox` example, the `add_file` action somehow is not able to get the `Files` collection, hence throwing the `Unable to access 'Files' collection` error.

**Comment by andrewxhill** [comment]
Just noting that this issue has been migrated from the js-examples repo. The issue refers to the example https://github.com/textileio/js-examples/tree/master/react-3box-threadsdb.

**Comment by andrewxhill** [comment]
all updated, e.g. https://docs.textile.io/tutorials/hub/web-app/
