### ISSUE TITLE
Make timeout for Auth longer by default

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-hub#372]
Say 1 hr?

**Comment by Jewcub** [comment]
At least a day please, or up to a month

**Comment by carsonfarmer** [comment]
We have to be careful here. The timeout is for the developers protection, not the Hub. The longer the timeout, the longer a malicious peer can be pinning data under a given developer account. But note also that this timeout is 100% under the control of the developer, not the Hub. 

This token as is, is slightly different from a standard web token, because it is issued by a developer for access to their Hub APIs (vs by the Hub). So these long expiration times can be unsafe. We do have to think carefully about them.

**Comment by Jewcub** [comment]
Truly. But in the refactor you will start using refresh tokens, no? So that can negate this issue. How about making it a day max just so current apps until the refactor can offer a decent UX



---Original---

**Comment by carsonfarmer** [comment]
This has been completed in https://github.com/textileio/js-threads/pull/525. It is also _much_ easier to set app-specific timeouts and defaults.
