### ISSUE TITLE
Client.withUserAuth does not work without explicitly supplying textile host URL

### ISSUE THREAD

**Issue by Jewcub** [textileio/js-hub#375]
can't connect without explicit API URL. Using this now:
```js
const TEXTILE_API=https://api.textile.io:3447
Client.withUserAuth(await loginCallback(), TEXTILE_API);
```
hub url should be hard coded default

**Comment by carsonfarmer** [comment]
Which version of hub are you running @Jewcub? In master the hub is the default host string: https://github.com/textileio/js-threads/blob/master/packages/client/src/index.ts#L113. Is it possible it was getting an empty string or other value other than undefined?

**Comment by Jewcub** [comment]
sorry, works with latest version
    "@textile/hub": "^0.4.1",
