### ISSUE TITLE
Unexpected behaviour of methods buckets.pullPath and buckets.pullIpfsPath.

### ISSUE THREAD

**Issue by theabdulmateen** [textileio/js-hub#377]
Hi, I have been working on a __react-native__ project in which I make use of textile buckets to push files to IPFS and retrieve it using the `buckets.pulIIpfsPath` but the file content seems to be corrupted. I have also tried the `buckets.pullPath` but it doesn't seem to work either.

I make use of [react-native-fs](https://github.com/itinance/react-native-fs) to read and write binary files

pushPath method:
```javascript
const content = await RNFS.readFile(uri, 'base64');
const _file = {
	path: '/' + file.name,
	content: Buffer.from(content),
};

const pushResult = await this.state.buckets.pushPath(this.state.bucketKey, file.name, _file);
```
the file uri is of format: `content://path/to/file`

Then I do this which is similar to the example provided here in [bucket-photo-gallery](https://github.com/textileio/js-examples/blob/master/bucket-photo-gallery/src/App.tsx) line 182 and line 214:
```javascript
const ipfsFilePath = pushResult.root;
const pullResult = await this.state.buckets.pullIpfsPath(ipfsFilePath);
const { value } = await pullResult.next();
let buffer = '';
for (var i = 0; i < value.length; i++) {
	buffer += String.fromCharCode(value[i]);
}
```
Is this the correct way of getting the `value` back? Should I not iterate over the `pullResult` as it is an `AsyncIterableIterator<Uint8Array>`? If so, how do I do that?

The `buffer` here seems to be corrupted. I don't know what I'm doing wrong. Any help would be greatly appreciated.
Thanks.

Update: also note that I am not able to iterate over the `pullResult` like so:
```javascript
for await (const chunk of pullResult) {
	console.log('chunk: ', chunk);
}
```
it throws this error: `TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.`

**Comment by carsonfarmer** [comment]
Hi @theabdulmateen , you update is the correct way to consume the AsyncIterableIterator<Uint8Array> that get's returned from `buckets.pullIIpfsPath`... but you don't need to await it. I think your error above stems from only having _part_ of the expected buffer, you'll want the whole thing.

```
const ipfsFilePath = pushResult.root;
const pullResult = this.state.buckets.pullIpfsPath(ipfsFilePath);
const chunks = []
for await (const chunk of pullResult) {
	console.log('chunk: ', chunk);
        chunks.push(chunk)
}
```

If you want to combine the whole thing into a single Uint8Array, something like this would work:

```
const  combined = Int8Array.from(Array.prototype.concat(...chunks.map(a => Array.from(a))));
```

Now you can do things like `Buffer.from()`, or work with your file bytes.

**Comment by theabdulmateen** [comment]
Hi @carsonfarmer thank you for your reply.

So I tried to consume the `pullResult` like you suggested:
```javascript
const pullResult = this.state.buckets.pullIpfsPath(ipfsFilePath);
console.log('pullResult: ', pullResult);
let chunks = [];
for await (const chunk of pullResult) {
	console.log('chunk: ', chunk);
	chunk.push(chunk);
}
console.log('chunks: ', chunks);
```
but unfortunately, I get the same error:
```
ExceptionsManager.js:179 TypeError: Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at k (index.js:12)
    at index.js:95
    at p (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.t.<computed> [as next] (runtime.js:97)
    at p (runtime.js:45)
    at o (runtime.js:135)
    at runtime.js:170
    at c (core.js:45)
    at X (core.js:200)
R @ ExceptionsManager.js:179
n @ backend.js:32
B @ LogBox.js:148
y @ LogBox.js:59
console.error @ LogBox.js:33
console.error @ muteWarnings.fx.js:27
(anonymous) @ index.js:137
p @ runtime.js:45
(anonymous) @ runtime.js:274
t.<computed> @ runtime.js:97
p @ runtime.js:45
o @ runtime.js:135
(anonymous) @ runtime.js:147
f @ core.js:37
(anonymous) @ core.js:123
(anonymous) @ JSTimers.js:274
y @ JSTimers.js:130
x @ JSTimers.js:181
callImmediates @ JSTimers.js:441
value @ MessageQueue.js:387
(anonymous) @ MessageQueue.js:135
value @ MessageQueue.js:364
value @ MessageQueue.js:134
value @ MessageQueue.js:112
(anonymous) @ debuggerWorker.cff11639.js:4
```

**Comment by carsonfarmer** [comment]
Ah ok, I'm seeing the error you're getting now. It looks like your build env doesn't support async iterators? Are you using Metro for this app?

Here's one possible work around:

```
const pullResult = this.state.buckets.pullIpfsPath(ipfsFilePath);
console.log('pullResult: ', pullResult);
const chunks = [];
const iterator = pullResult[Symbol.asyncIterator]();
while (chunks.length < Infinity) {
    const { value, done } = await iterator.next();
    if (done) break;
    chunks.push(value);
    console.log(value);
}
```

**Comment by carsonfarmer** [comment]
If that doesn't work, the returned pullResult itself _is_ an async iterator, so you can probably just call next on it directly:

```
const pullResult = this.state.buckets.pullIpfsPath(ipfsFilePath);
console.log('pullResult: ', pullResult);
const chunks = [];
while (chunks.length < Infinity) {
    const { value, done } = await pullResult.next();
    if (done) break;
    chunks.push(value);
    console.log(value);
}
```

**Comment by theabdulmateen** [comment]
Thank you for your reply, yes I am using metro bundler, 

So I tried both methods of retrieving the complete value but it seems that the loop gets broken after getting `value` once and it looks like the final value `chunks` gives the same buffer string as what was retrieved from my attempt in the initial post

**Comment by carsonfarmer** [comment]
Ok, so if you aren't getting any errors from the loop, then it seems your buffer is correct? Are you using an encrypted bucket by chance? What is the content of the buffer value, and what was originally pushed? Are you able to create a small reproducible example we can test?

**Comment by carsonfarmer** [comment]
Looks like a base64 encoded string? So you have a Uint8Array of base64 encoded bytes. Perhaps this might be useful to decode it from UInt8Array? https://gist.github.com/enepomnyaschih/72c423f727d395eeaa09697058238727

**Comment by carsonfarmer** [comment]
You could also use Buffer.from on the Uint8Array and then use the Buffer to encode/decode the content.

**Comment by theabdulmateen** [comment]
Ok so yes, the bucket was encrypted and this is definitely my fault and to give you an idea of what I am trying to achieve is: 
1. user opens a bucket and stores a file on the IPFS using the `buckets` and the `bucketKey` generated.
2. share the `pushResult.root` to another user who then creates an instance of his own `buckets` and `bucketKey` and I was naive to think that the IPFS path itself would be enough to retrieve the file.

since the buckets were encrypted the receiver creates a new bucket altogether and that is probably where the problem stems.

so to solve this I assume I would need access to the `threadID` of the bucket that contains the files. This isn't the same as the `bucketKey` is it? If it isn't how do I retrieve it. Do I need to access it from the links generated from `buckets.links()` or is there a better way?

I apologize for the confusion.

**Comment by theabdulmateen** [comment]
Also to answer your questions, I read a .jpg file using RNFS with base64 encoding and passed it to `pushPath` with `content: Buffer.from(content)` as mentioned in my initial post.

After retrieving the value from `pullIpfsPath` the file that was written back was only of around 0B - 788B which could be the `.textileseed` stored on the new bucket the receiver generated.
