### ISSUE TITLE
Update with users api

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-hub#395]
- [x] Create new Users api method for thread listing & inbox/sendbox
- [x] Refactor auth to better share across Buckets/Users
- [x] Update examples with breaking changes
- [ ] Update core docs: https://github.com/textileio/docs/issues/203

**Comment by carsonfarmer** [comment]
Is this ticket still relevant @andrewxhill ?

**Comment by andrewxhill** [comment]
complete
