### ISSUE TITLE
meme-marketplace react app conflict - yarn.lock AND package-lock.json file

### ISSUE THREAD

**Issue by tgrecojs** [textileio/js-hub#425]
I'm new to the filecoin ecosystem so today I decided to spend time working through the  [meme-marketplace](https://docs.filecoin.io/build/examples/meme-marketplace) tutorial on the filecoin website. I thought it was a really great intro for new users such as myself. It allowed me to gain an understanding on how these different tools work together, so many thanks to whoever was involved in getting that together! ❤️ 

I did run into a problem running the front-end code though, which is the reason I'm opening this issue. The "marketplace" folder, which contains the react app, also contains both a `package-lock.json` and a `yarn.lock` file. I'm pretty sure `npm` is supposed to complain about this but I didn't receive any such info in the command line. Luckily it wasn't too long of a time period before I noticed this, or else I would've been able to get the entire app up and running. 

All I had to do to get the front-end in a working state was remove the `package-lock.json` file, and then execute the `yarn` command. From there I used `yarn start` to run the app, but `npm start` would've worked just as well. The main thing is that these files are the lockfiles for 2 separate, competing package managers, and they don't play nicely with one another.

Below are links to the react code, as well as the conflicting files. Again, all that needs to be done is removal of the `package-lock.json`. only 2 seconds of work and could save a lot of potential headaches for others trying to onboard.

### React code base & files in question
* [meme-marketplace/marketplace](https://github.com/filecoin-shipyard/meme-marketplace/blob/master/marketplace)
* [meme-marketplace/marketplace/package-lock.json](https://github.com/filecoin-shipyard/meme-marketplace/blob/master/marketplace/package-lock.json)
* [meme-marketplace/marketplace/yarn.lock](https://github.com/filecoin-shipyard/meme-marketplace/blob/master/marketplace/yarn.lock)
### meme-marketplace/marketplace folder

**Comment by tgrecojs** [comment]
Created a PR for this. Let me know if this is the right place for merge, or if I need to open up PR for the textile/js-hub repo.

**Comment by andrewxhill** [comment]
Looks like you added it to the right place
