### ISSUE TITLE
Expose method for apps to increase auth timeout

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-hub#478]
It doesn't look easily possible in withKeyInfo at least, possibly other helper methods.

cc @carsonfarmer in case you see a quick fix

**Comment by carsonfarmer** [comment]
`withKeyInfo` doesn't currently support it, but the `Context.withKeyInfo` does take a `Date` object (https://github.com/textileio/js-threads/blob/master/packages/client/src/index.ts#L207), so we could add an arg to `Client. withKeyInfo` to take a date or even a duration (to compute the Date offset).

**Comment by carsonfarmer** [comment]
This could also be added to `withUserAuth`. Not also the "quick fix" here is to use an auth callback that returns a `UserAuth` object with a longer timeout using `createUserAuth` from `@textile/security` (https://github.com/textileio/js-threads/blob/master/packages/security/src/index.ts#L128).

**Comment by jimmylee** [comment]
Can I get some guidance if there is something I could quickly add here? https://github.com/filecoin-project/slate/blob/main/node_common/utilities.js#L85

**Comment by carsonfarmer** [comment]
There's not much possible just yet, as those particular APIs I mentioned would have to be updated first. Is this an immediate blocker? I might be able to prioritize a "quick fix" if yes...?

**Comment by jimmylee** [comment]
This prevents users with slow internet connections to get past ~10mb to ~20mb uploads at the moment. Tested this morning.

For myself, my uploads stop succeeding beyond ~200mb on an internet connection with: 300mbps up and 300mbps down

I believe this fix will allow for people to get file uploads as large as a GB. Since buckets are limited to 1GB I think as long as people are able to upload 100mb - 200mb files consistently we're in a good place.

**Comment by carsonfarmer** [comment]
Here's a really simple fix: https://github.com/textileio/js-hub/pull/479 that exposes the date param to allow longer timeouts. I've also extended the default timeout to 30 minutes here: https://github.com/textileio/js-threads/pull/525, though that is really just a "nice to have" versus an actual requirement. For your own project, simply specifying a Date about X minutes into the future would be sufficient, once this gets merged/released.

**Comment by jimmylee** [comment]
Thank you @carsonfarmer this makes my day.

I'll try to stay in sync for when to version bump.
