### ISSUE TITLE
Add Node transport by env

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-hub#596]
https://github.com/textileio/js-hub/blob/a62eb930868b2f3f7621a98f485663e142eb524f/packages/grpc-connection/src/index.ts#L19

@asutula is doing this in pow

```js
export const getTransport = (): grpc.TransportFactory | undefined =>
  isNode ? NodeHttpTransport() : undefined
```

not sure if we need it here or if it is redundant with other things we are doing. so needs deeper look, just recording.

**Comment by asutula** [comment]
I don't think this is needed because the Node transport doesn't support client or bidirectional streams. For this reason, Powergate now uses only the Textile `WebSocketTransport` for browser and Node.
